# Generated by Django 4.2.4 on 2023-08-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeImage',
            field=models.ImageField(upload_to='RacipeImg'),
        ),
    ]
